packages:
  - server
  - web
  - types
  - shared

catalog:
  '@typescript-eslint/eslint-plugin': ^8.55.0
  '@typescript-eslint/parser': ^8.55.0
  dayjs: ^1.11.14
  eslint: 9.39.2
  lodash-es: ^4.17.21
  random-js: 2.1.0
  typescript: 5.9.3
  zod: ^4.3.6

enablePrePostScripts: true
