/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';
import { CachedImageTable } from './schema/CachedImage';
import {
  ChannelCustomShowsTable,
  ChannelFallbackTable,
  ChannelFillerShowTable,
  ChannelProgramsTable,
  ChannelTable,
} from './schema/Channel';
import { CustomShowContentTable, CustomShowTable } from './schema/CustomShow';
import { FillerShowContentTable, FillerShowTable } from './schema/FillerShow';
import { MediaSourceTable } from './schema/MediaSource';
import { MikroOrmMigrations } from './schema/MikroOrmMigrations';
import { ProgramTable } from './schema/Program';
import { ProgramExternalIdTable } from './schema/ProgramExternalId';
import { ProgramGroupingTable } from './schema/ProgramGrouping';
import { ProgramGroupingExternalId } from './schema/ProgramGroupingExternalId';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface DB {
  cachedImage: CachedImageTable;
  channel: ChannelTable;
  channelCustomShows: ChannelCustomShowsTable;
  channelFallback: ChannelFallbackTable;
  channelFillerShow: ChannelFillerShowTable;
  channelPrograms: ChannelProgramsTable;
  customShow: CustomShowTable;
  customShowContent: CustomShowContentTable;
  fillerShow: FillerShowTable;
  fillerShowContent: FillerShowContentTable;
  mediaSource: MediaSourceTable;
  mikroOrmMigrations: MikroOrmMigrations;
  program: ProgramTable;
  programExternalId: ProgramExternalIdTable;
  programGrouping: ProgramGroupingTable;
  programGroupingExternalId: ProgramGroupingExternalId;
}
