name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['user-issue', 'triage']
assignees:
  - chrisbenincasa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our Tunarr are you running?
      placeholder: '1.0.0'
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: FFMPEG encoder type
      description: If this issue is related to streaming, please provide which type of encoder family you are using
      options:
        - Software
        - CUDA (Nvidia)
        - VAAPI
        - VideoToolbox (macOS)
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: What browser did you experience the the problem on?
      placeholder: 'ex: Chrome 122.0.6261.128'
  - type: input
    id: os
    attributes:
      label: What operating system are you using?
      placeholder: 'ex: Windows 8.1'
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Be sure to check both the server and the browser console logs!
      render: shell
