/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WelcomeImport } from './routes/welcome'
import { Route as SystemImport } from './routes/system'
import { Route as SettingsImport } from './routes/settings'
import { Route as SearchImport } from './routes/search'
import { Route as GuideImport } from './routes/guide'
import { Route as SchedulesRouteImport } from './routes/schedules_/route'
import { Route as ChannelsRouteImport } from './routes/channels_/route'
import { Route as IndexImport } from './routes/index'
import { Route as SystemIndexImport } from './routes/system/index'
import { Route as SchedulesIndexImport } from './routes/schedules_/index'
import { Route as MediasourcesIndexImport } from './routes/media_sources_/index'
import { Route as LibraryIndexImport } from './routes/library/index'
import { Route as ChannelsIndexImport } from './routes/channels_/index'
import { Route as SystemTroubleshootImport } from './routes/system/troubleshoot'
import { Route as SystemTasksImport } from './routes/system/tasks'
import { Route as SystemLogsImport } from './routes/system/logs'
import { Route as SystemDebugImport } from './routes/system/debug'
import { Route as SettingsXmltvImport } from './routes/settings/xmltv'
import { Route as SettingsSourcesImport } from './routes/settings/sources'
import { Route as SettingsScannerImport } from './routes/settings/scanner'
import { Route as SettingsHdhrImport } from './routes/settings/hdhr'
import { Route as SettingsGeneralImport } from './routes/settings/general'
import { Route as SettingsFfmpegImport } from './routes/settings/ffmpeg'
import { Route as SettingsFeaturesImport } from './routes/settings/features'
import { Route as SchedulesNewImport } from './routes/schedules_/new'
import { Route as LibraryFillersImport } from './routes/library/fillers'
import { Route as LibraryCustomShowsImport } from './routes/library/custom-shows'
import { Route as ChannelsTestImport } from './routes/channels_/test'
import { Route as ChannelsNewImport } from './routes/channels_/new'
import { Route as SchedulesScheduleIdRouteImport } from './routes/schedules_/$scheduleId/route'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels_/$channelId/route'
import { Route as SchedulesScheduleIdIndexImport } from './routes/schedules_/$scheduleId/index'
import { Route as MediasourcesMediaSourceIdIndexImport } from './routes/media_sources_/$mediaSourceId/index'
import { Route as LibraryTrashIndexImport } from './routes/library/trash_/index'
import { Route as LibrarySmartcollectionsIndexImport } from './routes/library/smart_collections/index'
import { Route as ChannelsChannelIdIndexImport } from './routes/channels_/$channelId/index'
import { Route as SettingsFfmpegNewImport } from './routes/settings/ffmpeg_/new'
import { Route as SettingsFfmpegConfigIdImport } from './routes/settings/ffmpeg_/$configId'
import { Route as MediaProgramTypeProgramIdImport } from './routes/media_/$programType.$programId'
import { Route as LibrarySmartcollectionsIdImport } from './routes/library/smart_collections/$id'
import { Route as ChannelsChannelIdWatchImport } from './routes/channels_/$channelId/watch'
import { Route as LibraryFillersNewRouteImport } from './routes/library/fillers_/new/route'
import { Route as LibraryFillersFillerIdRouteImport } from './routes/library/fillers_/$fillerId/route'
import { Route as LibraryCustomShowsNewRouteImport } from './routes/library/custom-shows_/new/route'
import { Route as LibraryCustomShowsShowIdRouteImport } from './routes/library/custom-shows_/$showId/route'
import { Route as LibraryFillersNewIndexImport } from './routes/library/fillers_/new/index'
import { Route as LibraryCustomShowsNewIndexImport } from './routes/library/custom-shows_/new/index'
import { Route as ChannelsChannelIdProgrammingIndexImport } from './routes/channels_/$channelId/programming/index'
import { Route as ChannelsChannelIdEditIndexImport } from './routes/channels_/$channelId/edit/index'
import { Route as SchedulesScheduleIdSlotsNewImport } from './routes/schedules_/$scheduleId/slots_/new'
import { Route as SchedulesScheduleIdSlotsIdImport } from './routes/schedules_/$scheduleId/slots_/$id'
import { Route as MediasourcesMediaSourceIdLibrariesLibraryIdImport } from './routes/media_sources_/$mediaSourceId/libraries_.$libraryId'
import { Route as LibraryFillersNewProgrammingImport } from './routes/library/fillers_/new/programming'
import { Route as LibraryFillersFillerIdProgrammingImport } from './routes/library/fillers_/$fillerId/programming'
import { Route as LibraryFillersFillerIdEditImport } from './routes/library/fillers_/$fillerId/edit'
import { Route as LibraryCustomShowsNewProgrammingImport } from './routes/library/custom-shows_/new/programming'
import { Route as LibraryCustomShowsShowIdProgrammingImport } from './routes/library/custom-shows_/$showId/programming'
import { Route as LibraryCustomShowsShowIdEditImport } from './routes/library/custom-shows_/$showId/edit'
import { Route as ChannelsChannelIdProgrammingTimeSlotEditorImport } from './routes/channels_/$channelId/programming/time-slot-editor'
import { Route as ChannelsChannelIdProgrammingSlotEditorImport } from './routes/channels_/$channelId/programming/slot-editor'
import { Route as ChannelsChannelIdProgrammingAddImport } from './routes/channels_/$channelId/programming/add'

// Create/Update Routes

const WelcomeRoute = WelcomeImport.update({
  path: '/welcome',
  getParentRoute: () => rootRoute,
} as any)

const SystemRoute = SystemImport.update({
  path: '/system',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const GuideRoute = GuideImport.update({
  path: '/guide',
  getParentRoute: () => rootRoute,
} as any)

const SchedulesRouteRoute = SchedulesRouteImport.update({
  path: '/schedules',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsRouteRoute = ChannelsRouteImport.update({
  path: '/channels',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SystemIndexRoute = SystemIndexImport.update({
  path: '/',
  getParentRoute: () => SystemRoute,
} as any)

const SchedulesIndexRoute = SchedulesIndexImport.update({
  path: '/',
  getParentRoute: () => SchedulesRouteRoute,
} as any)

const MediasourcesIndexRoute = MediasourcesIndexImport.update({
  path: '/media_sources/',
  getParentRoute: () => rootRoute,
} as any)

const LibraryIndexRoute = LibraryIndexImport.update({
  path: '/library/',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsIndexRoute = ChannelsIndexImport.update({
  path: '/',
  getParentRoute: () => ChannelsRouteRoute,
} as any)

const SystemTroubleshootRoute = SystemTroubleshootImport.update({
  path: '/troubleshoot',
  getParentRoute: () => SystemRoute,
} as any)

const SystemTasksRoute = SystemTasksImport.update({
  path: '/tasks',
  getParentRoute: () => SystemRoute,
} as any)

const SystemLogsRoute = SystemLogsImport.update({
  path: '/logs',
  getParentRoute: () => SystemRoute,
} as any)

const SystemDebugRoute = SystemDebugImport.update({
  path: '/debug',
  getParentRoute: () => SystemRoute,
} as any)

const SettingsXmltvRoute = SettingsXmltvImport.update({
  path: '/xmltv',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsSourcesRoute = SettingsSourcesImport.update({
  path: '/sources',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsScannerRoute = SettingsScannerImport.update({
  path: '/scanner',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsHdhrRoute = SettingsHdhrImport.update({
  path: '/hdhr',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsGeneralRoute = SettingsGeneralImport.update({
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsFfmpegRoute = SettingsFfmpegImport.update({
  path: '/ffmpeg',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsFeaturesRoute = SettingsFeaturesImport.update({
  path: '/features',
  getParentRoute: () => SettingsRoute,
} as any)

const SchedulesNewRoute = SchedulesNewImport.update({
  path: '/new',
  getParentRoute: () => SchedulesRouteRoute,
} as any)

const LibraryFillersRoute = LibraryFillersImport.update({
  path: '/library/fillers',
  getParentRoute: () => rootRoute,
} as any)

const LibraryCustomShowsRoute = LibraryCustomShowsImport.update({
  path: '/library/custom-shows',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsTestRoute = ChannelsTestImport.update({
  path: '/test',
  getParentRoute: () => ChannelsRouteRoute,
} as any)

const ChannelsNewRoute = ChannelsNewImport.update({
  path: '/new',
  getParentRoute: () => ChannelsRouteRoute,
} as any)

const SchedulesScheduleIdRouteRoute = SchedulesScheduleIdRouteImport.update({
  path: '/$scheduleId',
  getParentRoute: () => SchedulesRouteRoute,
} as any)

const ChannelsChannelIdRouteRoute = ChannelsChannelIdRouteImport.update({
  path: '/$channelId',
  getParentRoute: () => ChannelsRouteRoute,
} as any)

const SchedulesScheduleIdIndexRoute = SchedulesScheduleIdIndexImport.update({
  path: '/',
  getParentRoute: () => SchedulesScheduleIdRouteRoute,
} as any)

const MediasourcesMediaSourceIdIndexRoute =
  MediasourcesMediaSourceIdIndexImport.update({
    path: '/media_sources/$mediaSourceId/',
    getParentRoute: () => rootRoute,
  } as any)

const LibraryTrashIndexRoute = LibraryTrashIndexImport.update({
  path: '/library/trash/',
  getParentRoute: () => rootRoute,
} as any)

const LibrarySmartcollectionsIndexRoute =
  LibrarySmartcollectionsIndexImport.update({
    path: '/library/smart_collections/',
    getParentRoute: () => rootRoute,
  } as any)

const ChannelsChannelIdIndexRoute = ChannelsChannelIdIndexImport.update({
  path: '/',
  getParentRoute: () => ChannelsChannelIdRouteRoute,
} as any)

const SettingsFfmpegNewRoute = SettingsFfmpegNewImport.update({
  path: '/ffmpeg/new',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsFfmpegConfigIdRoute = SettingsFfmpegConfigIdImport.update({
  path: '/ffmpeg/$configId',
  getParentRoute: () => SettingsRoute,
} as any)

const MediaProgramTypeProgramIdRoute = MediaProgramTypeProgramIdImport.update({
  path: '/media/$programType/$programId',
  getParentRoute: () => rootRoute,
} as any)

const LibrarySmartcollectionsIdRoute = LibrarySmartcollectionsIdImport.update({
  path: '/library/smart_collections/$id',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsChannelIdWatchRoute = ChannelsChannelIdWatchImport.update({
  path: '/watch',
  getParentRoute: () => ChannelsChannelIdRouteRoute,
} as any)

const LibraryFillersNewRouteRoute = LibraryFillersNewRouteImport.update({
  path: '/library/fillers/new',
  getParentRoute: () => rootRoute,
} as any)

const LibraryFillersFillerIdRouteRoute =
  LibraryFillersFillerIdRouteImport.update({
    path: '/library/fillers/$fillerId',
    getParentRoute: () => rootRoute,
  } as any)

const LibraryCustomShowsNewRouteRoute = LibraryCustomShowsNewRouteImport.update(
  {
    path: '/library/custom-shows/new',
    getParentRoute: () => rootRoute,
  } as any,
)

const LibraryCustomShowsShowIdRouteRoute =
  LibraryCustomShowsShowIdRouteImport.update({
    path: '/library/custom-shows/$showId',
    getParentRoute: () => rootRoute,
  } as any)

const LibraryFillersNewIndexRoute = LibraryFillersNewIndexImport.update({
  path: '/',
  getParentRoute: () => LibraryFillersNewRouteRoute,
} as any)

const LibraryCustomShowsNewIndexRoute = LibraryCustomShowsNewIndexImport.update(
  {
    path: '/',
    getParentRoute: () => LibraryCustomShowsNewRouteRoute,
  } as any,
)

const ChannelsChannelIdProgrammingIndexRoute =
  ChannelsChannelIdProgrammingIndexImport.update({
    path: '/programming/',
    getParentRoute: () => ChannelsChannelIdRouteRoute,
  } as any)

const ChannelsChannelIdEditIndexRoute = ChannelsChannelIdEditIndexImport.update(
  {
    path: '/edit/',
    getParentRoute: () => ChannelsChannelIdRouteRoute,
  } as any,
)

const SchedulesScheduleIdSlotsNewRoute =
  SchedulesScheduleIdSlotsNewImport.update({
    path: '/slots/new',
    getParentRoute: () => SchedulesScheduleIdRouteRoute,
  } as any)

const SchedulesScheduleIdSlotsIdRoute = SchedulesScheduleIdSlotsIdImport.update(
  {
    path: '/slots/$id',
    getParentRoute: () => SchedulesScheduleIdRouteRoute,
  } as any,
)

const MediasourcesMediaSourceIdLibrariesLibraryIdRoute =
  MediasourcesMediaSourceIdLibrariesLibraryIdImport.update({
    path: '/media_sources/$mediaSourceId/libraries/$libraryId',
    getParentRoute: () => rootRoute,
  } as any)

const LibraryFillersNewProgrammingRoute =
  LibraryFillersNewProgrammingImport.update({
    path: '/programming',
    getParentRoute: () => LibraryFillersNewRouteRoute,
  } as any)

const LibraryFillersFillerIdProgrammingRoute =
  LibraryFillersFillerIdProgrammingImport.update({
    path: '/programming',
    getParentRoute: () => LibraryFillersFillerIdRouteRoute,
  } as any)

const LibraryFillersFillerIdEditRoute = LibraryFillersFillerIdEditImport.update(
  {
    path: '/edit',
    getParentRoute: () => LibraryFillersFillerIdRouteRoute,
  } as any,
)

const LibraryCustomShowsNewProgrammingRoute =
  LibraryCustomShowsNewProgrammingImport.update({
    path: '/programming',
    getParentRoute: () => LibraryCustomShowsNewRouteRoute,
  } as any)

const LibraryCustomShowsShowIdProgrammingRoute =
  LibraryCustomShowsShowIdProgrammingImport.update({
    path: '/programming',
    getParentRoute: () => LibraryCustomShowsShowIdRouteRoute,
  } as any)

const LibraryCustomShowsShowIdEditRoute =
  LibraryCustomShowsShowIdEditImport.update({
    path: '/edit',
    getParentRoute: () => LibraryCustomShowsShowIdRouteRoute,
  } as any)

const ChannelsChannelIdProgrammingTimeSlotEditorRoute =
  ChannelsChannelIdProgrammingTimeSlotEditorImport.update({
    path: '/programming/time-slot-editor',
    getParentRoute: () => ChannelsChannelIdRouteRoute,
  } as any)

const ChannelsChannelIdProgrammingSlotEditorRoute =
  ChannelsChannelIdProgrammingSlotEditorImport.update({
    path: '/programming/slot-editor',
    getParentRoute: () => ChannelsChannelIdRouteRoute,
  } as any)

const ChannelsChannelIdProgrammingAddRoute =
  ChannelsChannelIdProgrammingAddImport.update({
    path: '/programming/add',
    getParentRoute: () => ChannelsChannelIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRoute
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRoute
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemImport
      parentRoute: typeof rootRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeImport
      parentRoute: typeof rootRoute
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof ChannelsRouteImport
    }
    '/schedules/$scheduleId': {
      id: '/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof SchedulesScheduleIdRouteImport
      parentRoute: typeof SchedulesRouteImport
    }
    '/channels/new': {
      id: '/channels/new'
      path: '/new'
      fullPath: '/channels/new'
      preLoaderRoute: typeof ChannelsNewImport
      parentRoute: typeof ChannelsRouteImport
    }
    '/channels/test': {
      id: '/channels/test'
      path: '/test'
      fullPath: '/channels/test'
      preLoaderRoute: typeof ChannelsTestImport
      parentRoute: typeof ChannelsRouteImport
    }
    '/library/custom-shows': {
      id: '/library/custom-shows'
      path: '/library/custom-shows'
      fullPath: '/library/custom-shows'
      preLoaderRoute: typeof LibraryCustomShowsImport
      parentRoute: typeof rootRoute
    }
    '/library/fillers': {
      id: '/library/fillers'
      path: '/library/fillers'
      fullPath: '/library/fillers'
      preLoaderRoute: typeof LibraryFillersImport
      parentRoute: typeof rootRoute
    }
    '/schedules/new': {
      id: '/schedules/new'
      path: '/new'
      fullPath: '/schedules/new'
      preLoaderRoute: typeof SchedulesNewImport
      parentRoute: typeof SchedulesRouteImport
    }
    '/settings/features': {
      id: '/settings/features'
      path: '/features'
      fullPath: '/settings/features'
      preLoaderRoute: typeof SettingsFeaturesImport
      parentRoute: typeof SettingsImport
    }
    '/settings/ffmpeg': {
      id: '/settings/ffmpeg'
      path: '/ffmpeg'
      fullPath: '/settings/ffmpeg'
      preLoaderRoute: typeof SettingsFfmpegImport
      parentRoute: typeof SettingsImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralImport
      parentRoute: typeof SettingsImport
    }
    '/settings/hdhr': {
      id: '/settings/hdhr'
      path: '/hdhr'
      fullPath: '/settings/hdhr'
      preLoaderRoute: typeof SettingsHdhrImport
      parentRoute: typeof SettingsImport
    }
    '/settings/scanner': {
      id: '/settings/scanner'
      path: '/scanner'
      fullPath: '/settings/scanner'
      preLoaderRoute: typeof SettingsScannerImport
      parentRoute: typeof SettingsImport
    }
    '/settings/sources': {
      id: '/settings/sources'
      path: '/sources'
      fullPath: '/settings/sources'
      preLoaderRoute: typeof SettingsSourcesImport
      parentRoute: typeof SettingsImport
    }
    '/settings/xmltv': {
      id: '/settings/xmltv'
      path: '/xmltv'
      fullPath: '/settings/xmltv'
      preLoaderRoute: typeof SettingsXmltvImport
      parentRoute: typeof SettingsImport
    }
    '/system/debug': {
      id: '/system/debug'
      path: '/debug'
      fullPath: '/system/debug'
      preLoaderRoute: typeof SystemDebugImport
      parentRoute: typeof SystemImport
    }
    '/system/logs': {
      id: '/system/logs'
      path: '/logs'
      fullPath: '/system/logs'
      preLoaderRoute: typeof SystemLogsImport
      parentRoute: typeof SystemImport
    }
    '/system/tasks': {
      id: '/system/tasks'
      path: '/tasks'
      fullPath: '/system/tasks'
      preLoaderRoute: typeof SystemTasksImport
      parentRoute: typeof SystemImport
    }
    '/system/troubleshoot': {
      id: '/system/troubleshoot'
      path: '/troubleshoot'
      fullPath: '/system/troubleshoot'
      preLoaderRoute: typeof SystemTroubleshootImport
      parentRoute: typeof SystemImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexImport
      parentRoute: typeof ChannelsRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexImport
      parentRoute: typeof rootRoute
    }
    '/media_sources/': {
      id: '/media_sources/'
      path: '/media_sources'
      fullPath: '/media_sources'
      preLoaderRoute: typeof MediasourcesIndexImport
      parentRoute: typeof rootRoute
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/'
      fullPath: '/schedules/'
      preLoaderRoute: typeof SchedulesIndexImport
      parentRoute: typeof SchedulesRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexImport
      parentRoute: typeof SystemImport
    }
    '/library/custom-shows/$showId': {
      id: '/library/custom-shows/$showId'
      path: '/library/custom-shows/$showId'
      fullPath: '/library/custom-shows/$showId'
      preLoaderRoute: typeof LibraryCustomShowsShowIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/library/custom-shows/new': {
      id: '/library/custom-shows/new'
      path: '/library/custom-shows/new'
      fullPath: '/library/custom-shows/new'
      preLoaderRoute: typeof LibraryCustomShowsNewRouteImport
      parentRoute: typeof rootRoute
    }
    '/library/fillers/$fillerId': {
      id: '/library/fillers/$fillerId'
      path: '/library/fillers/$fillerId'
      fullPath: '/library/fillers/$fillerId'
      preLoaderRoute: typeof LibraryFillersFillerIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/library/fillers/new': {
      id: '/library/fillers/new'
      path: '/library/fillers/new'
      fullPath: '/library/fillers/new'
      preLoaderRoute: typeof LibraryFillersNewRouteImport
      parentRoute: typeof rootRoute
    }
    '/channels/$channelId/watch': {
      id: '/channels/$channelId/watch'
      path: '/watch'
      fullPath: '/channels/$channelId/watch'
      preLoaderRoute: typeof ChannelsChannelIdWatchImport
      parentRoute: typeof ChannelsChannelIdRouteImport
    }
    '/library/smart_collections/$id': {
      id: '/library/smart_collections/$id'
      path: '/library/smart_collections/$id'
      fullPath: '/library/smart_collections/$id'
      preLoaderRoute: typeof LibrarySmartcollectionsIdImport
      parentRoute: typeof rootRoute
    }
    '/media/$programType/$programId': {
      id: '/media/$programType/$programId'
      path: '/media/$programType/$programId'
      fullPath: '/media/$programType/$programId'
      preLoaderRoute: typeof MediaProgramTypeProgramIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/ffmpeg/$configId': {
      id: '/settings/ffmpeg/$configId'
      path: '/ffmpeg/$configId'
      fullPath: '/settings/ffmpeg/$configId'
      preLoaderRoute: typeof SettingsFfmpegConfigIdImport
      parentRoute: typeof SettingsImport
    }
    '/settings/ffmpeg/new': {
      id: '/settings/ffmpeg/new'
      path: '/ffmpeg/new'
      fullPath: '/settings/ffmpeg/new'
      preLoaderRoute: typeof SettingsFfmpegNewImport
      parentRoute: typeof SettingsImport
    }
    '/channels/$channelId/': {
      id: '/channels/$channelId/'
      path: '/'
      fullPath: '/channels/$channelId/'
      preLoaderRoute: typeof ChannelsChannelIdIndexImport
      parentRoute: typeof ChannelsChannelIdRouteImport
    }
    '/library/smart_collections/': {
      id: '/library/smart_collections/'
      path: '/library/smart_collections'
      fullPath: '/library/smart_collections'
      preLoaderRoute: typeof LibrarySmartcollectionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/library/trash/': {
      id: '/library/trash/'
      path: '/library/trash'
      fullPath: '/library/trash'
      preLoaderRoute: typeof LibraryTrashIndexImport
      parentRoute: typeof rootRoute
    }
    '/media_sources/$mediaSourceId/': {
      id: '/media_sources/$mediaSourceId/'
      path: '/media_sources/$mediaSourceId'
      fullPath: '/media_sources/$mediaSourceId'
      preLoaderRoute: typeof MediasourcesMediaSourceIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/schedules/$scheduleId/': {
      id: '/schedules/$scheduleId/'
      path: '/'
      fullPath: '/schedules/$scheduleId/'
      preLoaderRoute: typeof SchedulesScheduleIdIndexImport
      parentRoute: typeof SchedulesScheduleIdRouteImport
    }
    '/channels/$channelId/programming/add': {
      id: '/channels/$channelId/programming/add'
      path: '/programming/add'
      fullPath: '/channels/$channelId/programming/add'
      preLoaderRoute: typeof ChannelsChannelIdProgrammingAddImport
      parentRoute: typeof ChannelsChannelIdRouteImport
    }
    '/channels/$channelId/programming/slot-editor': {
      id: '/channels/$channelId/programming/slot-editor'
      path: '/programming/slot-editor'
      fullPath: '/channels/$channelId/programming/slot-editor'
      preLoaderRoute: typeof ChannelsChannelIdProgrammingSlotEditorImport
      parentRoute: typeof ChannelsChannelIdRouteImport
    }
    '/channels/$channelId/programming/time-slot-editor': {
      id: '/channels/$channelId/programming/time-slot-editor'
      path: '/programming/time-slot-editor'
      fullPath: '/channels/$channelId/programming/time-slot-editor'
      preLoaderRoute: typeof ChannelsChannelIdProgrammingTimeSlotEditorImport
      parentRoute: typeof ChannelsChannelIdRouteImport
    }
    '/library/custom-shows/$showId/edit': {
      id: '/library/custom-shows/$showId/edit'
      path: '/edit'
      fullPath: '/library/custom-shows/$showId/edit'
      preLoaderRoute: typeof LibraryCustomShowsShowIdEditImport
      parentRoute: typeof LibraryCustomShowsShowIdRouteImport
    }
    '/library/custom-shows/$showId/programming': {
      id: '/library/custom-shows/$showId/programming'
      path: '/programming'
      fullPath: '/library/custom-shows/$showId/programming'
      preLoaderRoute: typeof LibraryCustomShowsShowIdProgrammingImport
      parentRoute: typeof LibraryCustomShowsShowIdRouteImport
    }
    '/library/custom-shows/new/programming': {
      id: '/library/custom-shows/new/programming'
      path: '/programming'
      fullPath: '/library/custom-shows/new/programming'
      preLoaderRoute: typeof LibraryCustomShowsNewProgrammingImport
      parentRoute: typeof LibraryCustomShowsNewRouteImport
    }
    '/library/fillers/$fillerId/edit': {
      id: '/library/fillers/$fillerId/edit'
      path: '/edit'
      fullPath: '/library/fillers/$fillerId/edit'
      preLoaderRoute: typeof LibraryFillersFillerIdEditImport
      parentRoute: typeof LibraryFillersFillerIdRouteImport
    }
    '/library/fillers/$fillerId/programming': {
      id: '/library/fillers/$fillerId/programming'
      path: '/programming'
      fullPath: '/library/fillers/$fillerId/programming'
      preLoaderRoute: typeof LibraryFillersFillerIdProgrammingImport
      parentRoute: typeof LibraryFillersFillerIdRouteImport
    }
    '/library/fillers/new/programming': {
      id: '/library/fillers/new/programming'
      path: '/programming'
      fullPath: '/library/fillers/new/programming'
      preLoaderRoute: typeof LibraryFillersNewProgrammingImport
      parentRoute: typeof LibraryFillersNewRouteImport
    }
    '/media_sources/$mediaSourceId/libraries/$libraryId': {
      id: '/media_sources/$mediaSourceId/libraries/$libraryId'
      path: '/media_sources/$mediaSourceId/libraries/$libraryId'
      fullPath: '/media_sources/$mediaSourceId/libraries/$libraryId'
      preLoaderRoute: typeof MediasourcesMediaSourceIdLibrariesLibraryIdImport
      parentRoute: typeof rootRoute
    }
    '/schedules/$scheduleId/slots/$id': {
      id: '/schedules/$scheduleId/slots/$id'
      path: '/slots/$id'
      fullPath: '/schedules/$scheduleId/slots/$id'
      preLoaderRoute: typeof SchedulesScheduleIdSlotsIdImport
      parentRoute: typeof SchedulesScheduleIdRouteImport
    }
    '/schedules/$scheduleId/slots/new': {
      id: '/schedules/$scheduleId/slots/new'
      path: '/slots/new'
      fullPath: '/schedules/$scheduleId/slots/new'
      preLoaderRoute: typeof SchedulesScheduleIdSlotsNewImport
      parentRoute: typeof SchedulesScheduleIdRouteImport
    }
    '/channels/$channelId/edit/': {
      id: '/channels/$channelId/edit/'
      path: '/edit'
      fullPath: '/channels/$channelId/edit'
      preLoaderRoute: typeof ChannelsChannelIdEditIndexImport
      parentRoute: typeof ChannelsChannelIdRouteImport
    }
    '/channels/$channelId/programming/': {
      id: '/channels/$channelId/programming/'
      path: '/programming'
      fullPath: '/channels/$channelId/programming'
      preLoaderRoute: typeof ChannelsChannelIdProgrammingIndexImport
      parentRoute: typeof ChannelsChannelIdRouteImport
    }
    '/library/custom-shows/new/': {
      id: '/library/custom-shows/new/'
      path: '/'
      fullPath: '/library/custom-shows/new/'
      preLoaderRoute: typeof LibraryCustomShowsNewIndexImport
      parentRoute: typeof LibraryCustomShowsNewRouteImport
    }
    '/library/fillers/new/': {
      id: '/library/fillers/new/'
      path: '/'
      fullPath: '/library/fillers/new/'
      preLoaderRoute: typeof LibraryFillersNewIndexImport
      parentRoute: typeof LibraryFillersNewRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRoute.addChildren({
    ChannelsChannelIdRouteRoute: ChannelsChannelIdRouteRoute.addChildren({
      ChannelsChannelIdWatchRoute,
      ChannelsChannelIdIndexRoute,
      ChannelsChannelIdProgrammingAddRoute,
      ChannelsChannelIdProgrammingSlotEditorRoute,
      ChannelsChannelIdProgrammingTimeSlotEditorRoute,
      ChannelsChannelIdEditIndexRoute,
      ChannelsChannelIdProgrammingIndexRoute,
    }),
    ChannelsNewRoute,
    ChannelsTestRoute,
    ChannelsIndexRoute,
  }),
  SchedulesRouteRoute: SchedulesRouteRoute.addChildren({
    SchedulesScheduleIdRouteRoute: SchedulesScheduleIdRouteRoute.addChildren({
      SchedulesScheduleIdIndexRoute,
      SchedulesScheduleIdSlotsIdRoute,
      SchedulesScheduleIdSlotsNewRoute,
    }),
    SchedulesNewRoute,
    SchedulesIndexRoute,
  }),
  GuideRoute,
  SearchRoute,
  SettingsRoute: SettingsRoute.addChildren({
    SettingsFeaturesRoute,
    SettingsFfmpegRoute,
    SettingsGeneralRoute,
    SettingsHdhrRoute,
    SettingsScannerRoute,
    SettingsSourcesRoute,
    SettingsXmltvRoute,
    SettingsFfmpegConfigIdRoute,
    SettingsFfmpegNewRoute,
  }),
  SystemRoute: SystemRoute.addChildren({
    SystemDebugRoute,
    SystemLogsRoute,
    SystemTasksRoute,
    SystemTroubleshootRoute,
    SystemIndexRoute,
  }),
  WelcomeRoute,
  LibraryCustomShowsRoute,
  LibraryFillersRoute,
  LibraryIndexRoute,
  MediasourcesIndexRoute,
  LibraryCustomShowsShowIdRouteRoute:
    LibraryCustomShowsShowIdRouteRoute.addChildren({
      LibraryCustomShowsShowIdEditRoute,
      LibraryCustomShowsShowIdProgrammingRoute,
    }),
  LibraryCustomShowsNewRouteRoute: LibraryCustomShowsNewRouteRoute.addChildren({
    LibraryCustomShowsNewProgrammingRoute,
    LibraryCustomShowsNewIndexRoute,
  }),
  LibraryFillersFillerIdRouteRoute:
    LibraryFillersFillerIdRouteRoute.addChildren({
      LibraryFillersFillerIdEditRoute,
      LibraryFillersFillerIdProgrammingRoute,
    }),
  LibraryFillersNewRouteRoute: LibraryFillersNewRouteRoute.addChildren({
    LibraryFillersNewProgrammingRoute,
    LibraryFillersNewIndexRoute,
  }),
  LibrarySmartcollectionsIdRoute,
  MediaProgramTypeProgramIdRoute,
  LibrarySmartcollectionsIndexRoute,
  LibraryTrashIndexRoute,
  MediasourcesMediaSourceIdIndexRoute,
  MediasourcesMediaSourceIdLibrariesLibraryIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/channels",
        "/schedules",
        "/guide",
        "/search",
        "/settings",
        "/system",
        "/welcome",
        "/library/custom-shows",
        "/library/fillers",
        "/library/",
        "/media_sources/",
        "/library/custom-shows/$showId",
        "/library/custom-shows/new",
        "/library/fillers/$fillerId",
        "/library/fillers/new",
        "/library/smart_collections/$id",
        "/media/$programType/$programId",
        "/library/smart_collections/",
        "/library/trash/",
        "/media_sources/$mediaSourceId/",
        "/media_sources/$mediaSourceId/libraries/$libraryId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/channels": {
      "filePath": "channels_/route.tsx",
      "children": [
        "/channels/$channelId",
        "/channels/new",
        "/channels/test",
        "/channels/"
      ]
    },
    "/schedules": {
      "filePath": "schedules_/route.tsx",
      "children": [
        "/schedules/$scheduleId",
        "/schedules/new",
        "/schedules/"
      ]
    },
    "/guide": {
      "filePath": "guide.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx",
      "children": [
        "/settings/features",
        "/settings/ffmpeg",
        "/settings/general",
        "/settings/hdhr",
        "/settings/scanner",
        "/settings/sources",
        "/settings/xmltv",
        "/settings/ffmpeg/$configId",
        "/settings/ffmpeg/new"
      ]
    },
    "/system": {
      "filePath": "system.tsx",
      "children": [
        "/system/debug",
        "/system/logs",
        "/system/tasks",
        "/system/troubleshoot",
        "/system/"
      ]
    },
    "/welcome": {
      "filePath": "welcome.tsx"
    },
    "/channels/$channelId": {
      "filePath": "channels_/$channelId/route.tsx",
      "parent": "/channels",
      "children": [
        "/channels/$channelId/watch",
        "/channels/$channelId/",
        "/channels/$channelId/programming/add",
        "/channels/$channelId/programming/slot-editor",
        "/channels/$channelId/programming/time-slot-editor",
        "/channels/$channelId/edit/",
        "/channels/$channelId/programming/"
      ]
    },
    "/schedules/$scheduleId": {
      "filePath": "schedules_/$scheduleId/route.tsx",
      "parent": "/schedules",
      "children": [
        "/schedules/$scheduleId/",
        "/schedules/$scheduleId/slots/$id",
        "/schedules/$scheduleId/slots/new"
      ]
    },
    "/channels/new": {
      "filePath": "channels_/new.tsx",
      "parent": "/channels"
    },
    "/channels/test": {
      "filePath": "channels_/test.tsx",
      "parent": "/channels"
    },
    "/library/custom-shows": {
      "filePath": "library/custom-shows.tsx"
    },
    "/library/fillers": {
      "filePath": "library/fillers.tsx"
    },
    "/schedules/new": {
      "filePath": "schedules_/new.tsx",
      "parent": "/schedules"
    },
    "/settings/features": {
      "filePath": "settings/features.tsx",
      "parent": "/settings"
    },
    "/settings/ffmpeg": {
      "filePath": "settings/ffmpeg.tsx",
      "parent": "/settings"
    },
    "/settings/general": {
      "filePath": "settings/general.tsx",
      "parent": "/settings"
    },
    "/settings/hdhr": {
      "filePath": "settings/hdhr.tsx",
      "parent": "/settings"
    },
    "/settings/scanner": {
      "filePath": "settings/scanner.tsx",
      "parent": "/settings"
    },
    "/settings/sources": {
      "filePath": "settings/sources.tsx",
      "parent": "/settings"
    },
    "/settings/xmltv": {
      "filePath": "settings/xmltv.tsx",
      "parent": "/settings"
    },
    "/system/debug": {
      "filePath": "system/debug.tsx",
      "parent": "/system"
    },
    "/system/logs": {
      "filePath": "system/logs.tsx",
      "parent": "/system"
    },
    "/system/tasks": {
      "filePath": "system/tasks.tsx",
      "parent": "/system"
    },
    "/system/troubleshoot": {
      "filePath": "system/troubleshoot.tsx",
      "parent": "/system"
    },
    "/channels/": {
      "filePath": "channels_/index.tsx",
      "parent": "/channels"
    },
    "/library/": {
      "filePath": "library/index.tsx"
    },
    "/media_sources/": {
      "filePath": "media_sources_/index.tsx"
    },
    "/schedules/": {
      "filePath": "schedules_/index.tsx",
      "parent": "/schedules"
    },
    "/system/": {
      "filePath": "system/index.tsx",
      "parent": "/system"
    },
    "/library/custom-shows/$showId": {
      "filePath": "library/custom-shows_/$showId/route.tsx",
      "children": [
        "/library/custom-shows/$showId/edit",
        "/library/custom-shows/$showId/programming"
      ]
    },
    "/library/custom-shows/new": {
      "filePath": "library/custom-shows_/new/route.tsx",
      "children": [
        "/library/custom-shows/new/programming",
        "/library/custom-shows/new/"
      ]
    },
    "/library/fillers/$fillerId": {
      "filePath": "library/fillers_/$fillerId/route.tsx",
      "children": [
        "/library/fillers/$fillerId/edit",
        "/library/fillers/$fillerId/programming"
      ]
    },
    "/library/fillers/new": {
      "filePath": "library/fillers_/new/route.tsx",
      "children": [
        "/library/fillers/new/programming",
        "/library/fillers/new/"
      ]
    },
    "/channels/$channelId/watch": {
      "filePath": "channels_/$channelId/watch.tsx",
      "parent": "/channels/$channelId"
    },
    "/library/smart_collections/$id": {
      "filePath": "library/smart_collections/$id.tsx"
    },
    "/media/$programType/$programId": {
      "filePath": "media_/$programType.$programId.tsx"
    },
    "/settings/ffmpeg/$configId": {
      "filePath": "settings/ffmpeg_/$configId.tsx",
      "parent": "/settings"
    },
    "/settings/ffmpeg/new": {
      "filePath": "settings/ffmpeg_/new.tsx",
      "parent": "/settings"
    },
    "/channels/$channelId/": {
      "filePath": "channels_/$channelId/index.tsx",
      "parent": "/channels/$channelId"
    },
    "/library/smart_collections/": {
      "filePath": "library/smart_collections/index.tsx"
    },
    "/library/trash/": {
      "filePath": "library/trash_/index.tsx"
    },
    "/media_sources/$mediaSourceId/": {
      "filePath": "media_sources_/$mediaSourceId/index.tsx"
    },
    "/schedules/$scheduleId/": {
      "filePath": "schedules_/$scheduleId/index.tsx",
      "parent": "/schedules/$scheduleId"
    },
    "/channels/$channelId/programming/add": {
      "filePath": "channels_/$channelId/programming/add.tsx",
      "parent": "/channels/$channelId"
    },
    "/channels/$channelId/programming/slot-editor": {
      "filePath": "channels_/$channelId/programming/slot-editor.tsx",
      "parent": "/channels/$channelId"
    },
    "/channels/$channelId/programming/time-slot-editor": {
      "filePath": "channels_/$channelId/programming/time-slot-editor.tsx",
      "parent": "/channels/$channelId"
    },
    "/library/custom-shows/$showId/edit": {
      "filePath": "library/custom-shows_/$showId/edit.tsx",
      "parent": "/library/custom-shows/$showId"
    },
    "/library/custom-shows/$showId/programming": {
      "filePath": "library/custom-shows_/$showId/programming.tsx",
      "parent": "/library/custom-shows/$showId"
    },
    "/library/custom-shows/new/programming": {
      "filePath": "library/custom-shows_/new/programming.tsx",
      "parent": "/library/custom-shows/new"
    },
    "/library/fillers/$fillerId/edit": {
      "filePath": "library/fillers_/$fillerId/edit.tsx",
      "parent": "/library/fillers/$fillerId"
    },
    "/library/fillers/$fillerId/programming": {
      "filePath": "library/fillers_/$fillerId/programming.tsx",
      "parent": "/library/fillers/$fillerId"
    },
    "/library/fillers/new/programming": {
      "filePath": "library/fillers_/new/programming.tsx",
      "parent": "/library/fillers/new"
    },
    "/media_sources/$mediaSourceId/libraries/$libraryId": {
      "filePath": "media_sources_/$mediaSourceId/libraries_.$libraryId.tsx"
    },
    "/schedules/$scheduleId/slots/$id": {
      "filePath": "schedules_/$scheduleId/slots_/$id.tsx",
      "parent": "/schedules/$scheduleId"
    },
    "/schedules/$scheduleId/slots/new": {
      "filePath": "schedules_/$scheduleId/slots_/new.tsx",
      "parent": "/schedules/$scheduleId"
    },
    "/channels/$channelId/edit/": {
      "filePath": "channels_/$channelId/edit/index.tsx",
      "parent": "/channels/$channelId"
    },
    "/channels/$channelId/programming/": {
      "filePath": "channels_/$channelId/programming/index.tsx",
      "parent": "/channels/$channelId"
    },
    "/library/custom-shows/new/": {
      "filePath": "library/custom-shows_/new/index.tsx",
      "parent": "/library/custom-shows/new"
    },
    "/library/fillers/new/": {
      "filePath": "library/fillers_/new/index.tsx",
      "parent": "/library/fillers/new"
    }
  }
}
ROUTE_MANIFEST_END */
