name: Build *nix Nexe Binaries

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os:
          # TODO: Is there a way to get these working?
          # We don't build macOS Nexe binaries anymore because
          # of code signing.
          # - name: macos-13
          #   binary_name: macos-x64
          # - name: macos-14
          #   binary_name: macos-arm64
          # TODO: We can build ARM binaries, but we have to
          # use a docker container and extract them
          - name: ubuntu-latest
            binary_name: linux-x64
        node_version: [20.11.1]
    runs-on: ${{matrix.os.name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Python and NASM are required for compiling Node
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: ilammy/setup-nasm@v1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8.15.4
          run_install: false

      - name: Install nexe
        run: pnpm install -g nexe@next

      - name: Retrieve cached build
        id: cache-nexe-node-restore
        uses: actions/cache/restore@v4
        with:
          path: ./${{matrix.os.binary_name}}-${{matrix.node_version}}
          key: nexe-${{matrix.os.binary_name}}-${{matrix.node_version}}

      - name: Build ${{matrix.os.binary_name}}-${{matrix.node_version}} Nexe binary
        if: steps.cache-nexe-node-restore.outputs.cache-hit != 'true'
        run: nexe -t ${{matrix.os.binary_name}}-${{matrix.node_version}} --no-bundle --build --name dummy --verbose -i ./server/scripts/dummy-script.js

      - name: Copy Node binary
        if: steps.cache-nexe-node-restore.outputs.cache-hit != 'true'
        run: cp ~/.nexe/${{matrix.node_version}}/out/Release/node ./${{matrix.os.binary_name}}-${{matrix.node_version}}

      - name: Save Node binary to cache
        id: cache-nexe-node-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./${{matrix.os.binary_name}}-${{matrix.node_version}}
          key: ${{ steps.cache-nexe-node-restore.outputs.cache-primary-key }}

      - name: Upload pre-built Nexe binary
        uses: softprops/action-gh-release@v2
        with:
          name: Nexe Prebuilt Binaries
          tag_name: nexe-prebuild
          files: |
            ./${{matrix.os.binary_name}}-${{matrix.node_version}}
