name: Build Windows

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: ilammy/setup-nasm@v1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8.15.4
          run_install: false

      - name: Install nexe
        run: pnpm install -g nexe@next

      # - name: Install dependencies
      #   run: pnpm install

      # - name: Build Tunarr
      #   run: pnpm turbo bundle

      - name: Build Windows exe
        run: nexe -t windows-x64-20.11.1 --no-bundle --build --name dummy.exe --verbose -i ./server/scripts/dummy-script.js

      - name: Copy node binary
        run: xcopy C:\Users\runneradmin\.nexe\20.11.1\out\Release\node.exe .\
      
      - name: Rename Node binary
        run: ren node.exe windows-x64-20.11.1.exe

      - name: Upload pre-built Windows nexe
        uses: softprops/action-gh-release@v2
        with:
          name: nexe-windows-prebuild-20.11.1
          tag_name: nexe-prebuild
          files: |
            windows-x64-20.11.1.exe
